name: Deploy web app to Azure Static Web Apps

on:
  push:
    branches: [ "main" ]
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches: [ "main" ]

env:
  APP_LOCATION: "/dev/Interfaces & Usability course/readysettravel/"
  API_LOCATION: "api"
  APP_ARTIFACT_LOCATION: "build"
  AZURE_STATIC_WEB_APPS_API_TOKEN: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}

permissions:
  contents: read

jobs:
  check_secrets:
    runs-on: ubuntu-latest
    outputs:
      has_secrets: ${{ steps.check_secrets_step.outputs.has_secrets }}
    steps:
      - name: Check required secrets
        id: check_secrets_step
        run: |
          if [ -z "${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}" ]; then
            echo "Required secrets are missing. Skipping deployment.";
            echo "has_secrets=false" >> $GITHUB_ENV;
          else
            echo "All required secrets are available. Proceeding with deployment.";
            echo "has_secrets=true" >> $GITHUB_ENV;
          fi

  build_and_deploy_job:
    needs: check_secrets
    if: needs.check_secrets.outputs.has_secrets == 'true'
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Build And Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ env.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: ${{ env.APP_LOCATION }}
          api_location: ${{ env.API_LOCATION }}
          app_artifact_location: ${{ env.APP_ARTIFACT_LOCATION }}

  close_pull_request_job:
    needs: check_secrets
    if: needs.check_secrets.outputs.has_secrets == 'true' && github.event_name == 'pull_request' && github.event.action == 'closed'
    permissions:
      contents: none
    runs-on: ubuntu-latest
    steps:
      - name: Close Pull Request
        uses: Azure/static-web-apps-deploy@v1
        with:
          app_location: ${{ env.APP_LOCATION }}
          azure_static_web_apps_api_token: ${{ env.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: "close"

