name: Deploy web app to Azure Static Web Apps

on:
  push:
    branches: [ "main" ]

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3

      - name: Build And Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          app_location: "/dev/ Interfaces & Usability course/readysettravel/" # Corrected path as you specified
          api_location: "" # Not used for a basic static site
          output_location: "" # Not used for a basic static site, assuming no build process
