name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: List directory contents
      run: ls -R

    - name: Find package.json
      run: |
        PACKAGE_JSON_PATH=$(find . -name package.json | grep -v /node_modules/ | head -n 1)
        echo "PACKAGE_JSON_PATH=$PACKAGE_JSON_PATH" >> $GITHUB_ENV

    - name: Debug - Print package.json path
      run: echo "package.json found at $PACKAGE_JSON_PATH"

    - name: Install dependencies
      run: yarn install --frozen-lockfile
      working-directory: ${{ steps.find-package-json.outputs.PACKAGE_JSON_DIR }}

    - name: Build app
      run: yarn build
      working-directory: ${{ steps.find-package-json.outputs.PACKAGE_JSON_DIR }}
      env:
        CI: false
        PUBLIC_URL: /https://github.com/BradleyMatera/ReadySetTravelPages

    - name: Setup Pages
      uses: actions/configure-pages@v3

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v2
      with:
        path: ${{ steps.find-package-json.outputs.PACKAGE_JSON_DIR }}/build

    - name: Deploy to GitHub Pages
      id: deployment
      if: github.ref == 'refs/heads/main'
      uses: actions/deploy-pages@v2