name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: List directory contents
      run: ls -R

    - name: Find package.json
      id: find-package-json
      run: |
        PACKAGE_JSON=$(find . -name "package.json" -not -path "*/node_modules/*" -print -quit)
        if [ -z "$PACKAGE_JSON" ]; then
          echo "No package.json found"
          exit 1
        fi
        echo "PACKAGE_JSON_DIR=$(dirname $PACKAGE_JSON)" >> $GITHUB_OUTPUT
        echo "Package.json found in: $(dirname $PACKAGE_JSON)"

    - name: Install dependencies
      run: yarn install --frozen-lockfile
      working-directory: ${{ steps.find-package-json.outputs.PACKAGE_JSON_DIR }}

    - name: Build app
      run: yarn build
      working-directory: ${{ steps.find-package-json.outputs.PACKAGE_JSON_DIR }}
      env:
        CI: false
        PUBLIC_URL: /WDV-119-Bradley-Matera

    - name: Setup Pages
      uses: actions/configure-pages@v3

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v2
      with:
        path: ${{ steps.find-package-json.outputs.PACKAGE_JSON_DIR }}/build

    - name: Deploy to GitHub Pages
      id: deployment
      if: github.ref == 'refs/heads/main'
      uses: actions/deploy-pages@v2